print("Welcome to the tip calculator")
total_bill = input("What was the total bill? $")
percentage = input("What percentage tip would you like to give? 10, 12 or 15? ")
people = input("How may people to split the bill? ")
total_bill_as_float = float(total_bill)
percentage_as_int = int(percentage)
people_as_int = int(people)
tip = (total_bill_as_float / people_as_int) * (1 + percentage_as_int / 100)
final_tip = "{:.2f}".format(tip)
print(f"Each person should pay: ${final_tip}")
